### ISSUE TITLE
无法找到日志实现

### ISSUE THREAD

**Issue by ExplodingDragon2** [OPEN-EDGN/Logger4K#5]
## 系统信息

- Java 版本 ：11.0.7
- 打包工具：Gradle
- Kotlin版本：1.4.10
- 启用Java模块化：是

## 插件版本信息

- core：1.3.0
- logger-console ：1.3.0

**Comment by ExplodingFKL** [comment]
可能是模块化的问题，已发布修复补丁，你可以试试 1.3.1 版本看看问题解决了没。

**Comment by ExplodingDragon** [comment]
> ## 系统信息
> * Java 版本 ：11.0.7
> * 打包工具：Gradle
> * Kotlin版本：1.4.10
> * 启用Java模块化：是
> 
> ## 插件版本信息
> * core：1.3.0
> * logger-console ：1.3.0

可能是模块化的问题，已发布修复补丁，你可以试试 1.3.1 版本看看问题解决了没。

**Comment by ExplodingDragon** [comment]
> ## 系统信息
> * Java 版本 ：11.0.7
> * 打包工具：Gradle
> * Kotlin版本：1.4.10
> * 启用Java模块化：是
> 
> ## 插件版本信息
> * core：1.3.0
> * logger-console ：1.3.0

可以临时通过在main 方法下加入

```kotlin
PluginManager.registerPlugin(ConsolePlugin::class)
```
解决。
